# Generated by Django 6.0.2 on 2026-02-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('landlord', 'Landlord'), ('caretaker', 'Caretaker'), ('bookkeeper', 'Bookkeeper')], default='landlord', max_length=20),
        ),
    ]
