# Generated by Django 6.0.2 on 2026-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('total_units', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=255)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to='property_images/')),
            ],
        ),
    ]
