# Generated by Django 6.0.2 on 2026-02-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('claimed', 'Claimed'), ('unclaimed', 'Unclaimed')], default='unclaimed', max_length=20),
        ),
    ]
