# Generated by Django 6.0.2 on 2026-02-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='units.unit'),
        ),
    ]
